#' <%=ifelse(exists("test.results")     && test.results,       "@param test.results       either a numeric vector with p-values or an R6 object of class \\code{\\link[DiscreteTests]{DiscreteTestResults}} from package [`DiscreteTests`][DiscreteTests::DiscreteTests-package] for which a discrete FDR procedure is to be performed.","") %>
#' <%=ifelse(exists("pCDFlist")         && pCDFlist,           "@param pCDFlist           list of the supports of the CDFs of the p-values; each list item must be a numeric vector, which is sorted in increasing order and whose last element equals 1.","") %>
#' <%=ifelse(exists("alpha")            && alpha,              "@param alpha              single real number strictly between 0 and 1 specifying the target FDP.","") %>
#' <%=ifelse(exists("zeta")             && zeta,               "@param zeta               single real number strictly between 0 and 1 specifying the target probability of not exceeding the desired FDP. If `zeta = NULL` (the default), then `zeta` is chosen equal to `alpha`.","") %>
#' <%=ifelse(exists("direction")        && direction,          "@param direction          single character string specifying whether to perform the step-up (`\"su\`) or step-down (`\"sd\"`; the default) version of the Lehmann-Romano procedure.","") %>
#' <%=ifelse(exists("critical.values")  && critical.values,    "@param critical.values    single boolean indicating whether critical constants are to be computed.","") %>
#' <%=ifelse(exists("adaptive")         && adaptive,           "@param adaptive           single boolean indicating whether to conduct an adaptive procedure or not.","") %>
#' <%=ifelse(exists("exact")            && exact,              "@param exact              single boolean indicating whether to compute the Poisson-Binomial distribution exactly or by normal approximation.","") %>
#' <%=ifelse(exists("weights")          && weights,            "@param weights            numeric vector that contains the weights for the p-values.","") %>
#' <%=ifelse(exists("weighting.method") && weighting.method,   "@param weighting.method   single character string specifying whether to conduct arithmetic (`direction = \"AM\"`, the default) or geometric weighting (`direction = \"GM\"`) of p-values.","") %>
#' <%=ifelse(exists("select.threshold") && select.threshold,   "@param select.threshold   single real number strictly between 0 and 1 indicating the largest raw p-value to be considered, i.e. only p-values below this threshold are considered and the procedures are adjusted in order to take this selection effect into account; if `threshold = 1` (the default), all raw p-values are selected.","") %>
#' <%=ifelse(exists("pCDFlist.indices") && pCDFlist.indices,   "@param pCDFlist.indices   list of numeric vectors containing the test indices that indicate to which raw p-value each **unique** support in `pCDFlist` belongs; ignored if the lengths of `test.results` and `pCDFlist` are equal.","") %>
#' <%=ifelse(exists("triple.dots")      && triple.dots,        "@param ...                further arguments to be passed to or from other methods. They are ignored here.","") %>
